# fly.toml app configuration file generated for big-beef-tracker on 2023-06-04T13:22:59-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "big-beef-tracker"
primary_region = "dfw"
kill_signal = "SIGTERM"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "big-beef-tracker.fly.dev"
  PORT = "4001"
  SERVICE_TO_START = "big_beef"

[[services]]
  protocol = "tcp"
  internal_port = 4001
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
